# Generated by Django 5.2.16 on 2026-08-08 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='carbs_consumed',
            field=models.PositiveIntegerField(blank=True, help_text='in grams', null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='fats_consumed',
            field=models.PositiveIntegerField(blank=True, help_text='in grams', null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='protein_consumed',
            field=models.PositiveIntegerField(blank=True, help_text='in grams', null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('burnout', 'Burnout Warning'), ('plateau', 'Plateau Warning'), ('hydration', 'Hydration Warning')], max_length=15),
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='fitness.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'meal', 'date')},
            },
        ),
    ]
