# Generated by Django 5.2.16 on 2026-07-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_time',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='day_of_week',
            field=models.CharField(help_text='e.g. Monday, Tuesday', max_length=50),
        ),
    ]
