# Generated by Django 5.2.16 on 2026-08-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_dailylog_carbs_consumed_dailylog_fats_consumed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='ai_insight',
            field=models.TextField(blank=True, default=''),
        ),
    ]
