# Generated by Django 5.2.16 on 2026-07-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_alter_meal_meal_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='gif_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='meal',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
