# Generated by Django 5.2.16 on 2026-07-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_exercise_gif_url_exercise_image_url_meal_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='gif_url',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='image_url',
        ),
        migrations.AddField(
            model_name='exercise',
            name='custom_gif_url',
            field=models.URLField(blank=True, help_text='Paste a custom exercise GIF link here', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='custom_image_url',
            field=models.URLField(blank=True, help_text='Paste a custom food photo link here', max_length=500, null=True),
        ),
    ]
